### ISSUE TITLE
Stress-test the new render loop

### ISSUE THREAD

**Issue by Liebranca** [Liebranca/dsm#11]
Last commit I made a ridiculous number of changes to the global update function and introduced object culling into the mix. It works well in a small test scene but I have no idea how well it's going to scale.

So, test, measure, test and test again, fine-tune, fix, cry, you know the drill.

### Task list
- [x] Write scene export for `BlackMagic`
- [ ] Build test scene
- [ ] See how bad framerate can get
