### ISSUE TITLE
Unreliable framerate

### ISSUE THREAD

**Issue by Liebranca** [Liebranca/dsm#12]
Alright, so while doing some testing I've realized that the timekeeping functions from Zajec might be slightly off. Since we rely on these to drive the framerate I'd prefer making sure everything is working correctly, so... let's fix this mess before we do anything else.

### Task List

- [x] Revise the Zajec timekeeping functions.
- [x] Revise the mouselook methods. They're a bit "shaky" sometimes.
- [x] Implement some joystick input while we're at it. That's always fun.
