### ISSUE TITLE
Shader fixing

### ISSUE THREAD

**Issue by Liebranca** [Liebranca/dsm#3]
Future Lyeb, I really do hope you're feeling like putting in work because I have some more for you.

### TASK LIST

* [x] Move the source code to cpp source files
* [x] Figure out faster specular (or remove it)
* [x] Rethink normal map implementation

Yours truly, your past self.
