### ISSUE TITLE
float to frac16 conversion

### ISSUE THREAD

**Issue by Liebranca** [Liebranca/dsm#5]
### Task list

- [x] Create float range `(i*0.0078125 for i in 128)`
- [x] Split float at dot
- [x] Determine sign
- [x] Take closest decimal in range
- [x] Add rounding rules
- [x] Fuse bits into frac16
- [x] Move everything to lybyte and tidy up
