### ISSUE TITLE
C-like array & file handling

### ISSUE THREAD

**Issue by Liebranca** [Liebranca/dsm#6]
### Notes to self

1. Remember to use templates
2. Manage memory responsibly
3. Do nigh-paranoid level of error handling
4. Embrace pointer math

### Task list

* Create new file struct for lybyte
  * [x] Opening
  * [x] Closing
  * [x] Reading from stream
  * [x] Writing to new file

### 

* Create new dynamic array struct
  * [x] Initialization
  * [x] Modifying values at index
  * [x] Deallocation
