### ISSUE TITLE
Memory management, chapter one

### ISSUE THREAD

**Issue by Liebranca** [Liebranca/dsm#7]
Navigate through `lybyte/file.cpp` and `lytutils/evil.cpp` and determine possible sources of leaking.

Just to be *absolutely clear*, I know for a fact that the OS is freeing up all memory used during calls to `Zajec` -- it always does so, eventually that is. The point to this is adding an additional layer of security so that a resource monitor won't fire off on a false positive, making future maintenance not as much of a pain.

### Notes to self

1. For methods making use of `malloc`, declare pointers *before* the call. We need those addresses to explicitly free up all memory on a non-fatal exit , which would be lost when we return early with a failure. Wrapping these methods may prove convenient.

2. **USE FLAGS**. With proper failure codes, we can do proper cleanup.

### Task list

* [x] Wrap writing/reading methods
* [x] Rework error handling
* [x] Reestructure code to avoid early terminations
