### ISSUE TITLE
Write/read methods for ZJC_FileHandling

### ISSUE THREAD

**Issue by Liebranca** [Liebranca/dsm#8]
The current (wrapped) writing function for crk files `IN_writecrk` is faulty at appending. Furthermore, insertion of a larger chunk in place of a previous one results in overwrites of data outside the range of the older chunk. Expanding on current methods to streamline reading whole chunks of bytes at a time would be a huge improvement. If we can also design these methods to facilitate copying/buffering of chunks for later pasting in, that'd great.

### Task list

* [x] Define bytechunk
* [x] Read chunk from file
* [x] Redouble on paranoid memwards
* [x] Write chunk to file
* [x] Appending
* [x] Insertion
* [x] Deletion

**Comment by Liebranca** [comment]
Closed in e751bf8
